# Generated by Django 5.2.4 on 2025-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sells',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
