# Generated by Django 5.2.4 on 2025-07-26 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_sells'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
