# Generated by Django 5.2.4 on 2025-07-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pictures/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to='main.customer')),
            ],
        ),
    ]
