# Generated by Django 5.2.4 on 2025-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_customer_profile_picture_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profile_pictures/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
